// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMhJhK90pOvTf_Kz53uCH7Hi4saiaaODE',
    appId: '1:730271045267:web:5882cd4c0f8d5de4b0df66',
    messagingSenderId: '730271045267',
    projectId: 'chardham-tour-a08ac',
    authDomain: 'chardham-tour-a08ac.firebaseapp.com',
    storageBucket: 'chardham-tour-a08ac.appspot.com',
    measurementId: 'G-LN4NE07HNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWrY45_0x8CTsgf3M8BW9ZrhBtbqKhGD4',
    appId: '1:730271045267:android:399e60710f9d50e7b0df66',
    messagingSenderId: '730271045267',
    projectId: 'chardham-tour-a08ac',
    storageBucket: 'chardham-tour-a08ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfKZfv7Y1jKi8_NQcnzXj69Fy8LgnwiCA',
    appId: '1:730271045267:ios:1c02d414a608f791b0df66',
    messagingSenderId: '730271045267',
    projectId: 'chardham-tour-a08ac',
    storageBucket: 'chardham-tour-a08ac.appspot.com',
    androidClientId: '730271045267-39j78jo7kflo133iohe7q104icaq25if.apps.googleusercontent.com',
    iosClientId: '730271045267-fdvoef4evjrlvlo1e7pqp5e6iq5d97qf.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelFirebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfKZfv7Y1jKi8_NQcnzXj69Fy8LgnwiCA',
    appId: '1:730271045267:ios:8542c6ae77fc1c7ab0df66',
    messagingSenderId: '730271045267',
    projectId: 'chardham-tour-a08ac',
    storageBucket: 'chardham-tour-a08ac.appspot.com',
    androidClientId: '730271045267-39j78jo7kflo133iohe7q104icaq25if.apps.googleusercontent.com',
    iosClientId: '730271045267-1ji267qp102p96kgcjgtqbjlh4uh0qe7.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelFirebaseFlutter.RunnerTests',
  );
}
